name: job_test
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^7.7.0
  flutter_bloc: ^8.1.5
  dio: ^5.4.3+1
  injectable: ^2.4.2
  freezed: ^2.5.2
  dartz: ^0.10.1
  file_picker: ^8.0.3
  video_player: ^2.8.6
  firebase_core: ^2.31.1
  cloud_firestore: ^4.17.4
  uuid: ^4.4.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.1

flutter:
  uses-material-design: true