// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9B8wHfFPYXBoHFMe-j4N2duukiuq9pNQ',
    appId: '1:888736338634:web:27d1b9a770ee977fb5da33',
    messagingSenderId: '888736338634',
    projectId: 'jobtest-sokhib',
    authDomain: 'jobtest-sokhib.firebaseapp.com',
    storageBucket: 'jobtest-sokhib.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgjBzhZ4Cy5h7TcIUsiJZ08bcLVW2qkps',
    appId: '1:888736338634:android:78a46be9a43fd80cb5da33',
    messagingSenderId: '888736338634',
    projectId: 'jobtest-sokhib',
    storageBucket: 'jobtest-sokhib.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIdtY0P-PwFJsCkyppwki6X6CyTnzeybQ',
    appId: '1:888736338634:ios:a5ea7e4fb317def4b5da33',
    messagingSenderId: '888736338634',
    projectId: 'jobtest-sokhib',
    storageBucket: 'jobtest-sokhib.appspot.com',
    iosBundleId: 'uz.sokhib.jobTest',
  );
}
